### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined     at /home/runner/Heliactyl/index.js:149:80

### ISSUE THREAD

**Issue by conghal334** [Heliactyl/Heliactyl#3]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /home/runner/Heliactyl/index.js:149:80 help
    why is this errpr

**Comment by vachanmn123** [comment]
Can anyone help? I am facing the same error
