### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Clashplayer-PROTECT** [Heliactyl/Heliactyl#49]
/var/www/heliactyl/api/linkvertise.js:107
        return res.json({ cooldown: cooldowns[req.session.userinfo.id] ?? null })
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /var/www/heliactyl/index.js:156:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/var/www/heliactyl/index.js:155:10)

**Comment by NotPlex** [comment]
u need to upgrade to nodejs 16 and remove the folders starting with .
